/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class App */
#include<iostream>

#ifndef _Included_App
#define _Included_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     App
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_App_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
