/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class App */

#ifndef _Included_App
#define _Included_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     App
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_App_hello
  (JNIEnv *, jobject);

/*
 * Class:     App
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_App_close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     App
 * Method:    doSomething
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_App_doSomething
  (JNIEnv *, jobject, jint);

/*
 * Class:     App
 * Method:    getStructPointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_App_getStructPointer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
